### PR TITLE
Proposal: delete Twitter account

### PR DESCRIPTION
**Pull request by janosdebugs**
## Changes introduced with this PR

This proposal aims to delete the ContainerSSH Twitter account. Please discuss in the comments.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/ContainerSSH/community/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sanjacodes** [comment]
Maybe we should put this on ice until we have a decision from the CNCF around the sandboxing? Otherwise, I'm all for deleting and avoiding social media, so +1 from me (that's a vote for yes).

I think we can let this proposal stay open until the CNCF decision?

What's your opinions, @bencurio, @tsipinakis?

**Review by sanjacodes — APPROVED** [review]
See [comment](https://github.com/ContainerSSH/community/pull/3#issuecomment-1148538093). Approving as a vote for yes, though.

**Comment by bencurio** [comment]
I think that it may be worthwhile for the project to keep social channels, even if it only exist as a placeholder. This ensures that no one else can register our username.

At the moment, my opinion is to wait for the CNCF decision and leave this proposal open.

**Comment by tsipinakis** [comment]
I agree with @bencurio, I think keeping the username is important for the ContainerSSH branding. If we end up setting up an RSS feed on the website it would be trivial to setup a bot to post only new entries to Twitter while having minimal interaction/maintenance for the account.
My vote is also to delay this until we have an answer for CNCF and re-evaluate then.

**Comment by janosdebugs** [comment]
Closing proposal, postponing until we have an answer from CNCF.

**Pull request closed without merging**
